apiVersion: apps/v1
kind: Deployment
metadata:
  name: st2dce-prod
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: st2dce-prod
  template:
    metadata:
      labels:
        app: st2dce-prod
    spec:
      containers:
        - name: st2dce
          image: ${IMAGE_NAME}:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: st2dce-prod-service
  namespace: production
spec:
  selector:
    app: st2dce-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer