alertmanager:
  enabled: true

server:
  global:
    scrape_interval: 15s  # Scrape targets every 15 seconds
  extraScrapeConfigs: |
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod

  alertingRules:
    groups:
      - name: example
        rules:
          - alert: HighMemoryUsage
            expr: node_memory_Active_bytes / node_memory_MemTotal_bytes > 0.8
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: High memory usage detected
