apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: st2dce-dev
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: st2dce
  template:
    metadata:
      labels:
        app: st2dce
    spec:
      containers:
        - name: st2dce
          image: sabrinam2/st2dce:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: st2dce-dev-service
  namespace: development
spec:
  selector:
    app: st2dce-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP