apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: st2dce-dev
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: st2dce
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8080'
      labels:
        app: st2dce
    spec:
      containers:
        - name: st2dce
          image: sabrinam2/st2dce:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: st2dce-dev-service
  namespace: development
spec:
  selector:
    app: st2dce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP